# Generated by Django 4.0.1 on 2022-01-20 02:03

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
                ('hidden', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice'), ('CB', 'Checkboxes'), ('DP', 'Dropdown'), ('SC', 'Scale'), ('SA', 'Short Answer'), ('PA', 'LONG Answer')], max_length=2)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
