# Generated by Django 4.0.1 on 2022-01-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
