# Generated by Django 4.0.1 on 2022-01-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveyquestionchoice_hidden_surveysubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='range_default',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='range_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='range_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='range_step',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyquestionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.surveyquestion'),
        ),
        migrations.DeleteModel(
            name='SurveyQuestionScaleMeta',
        ),
    ]
