# Generated by Django 4.0.1 on 2022-01-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_surveyquestion_range_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='surveyquestionchoice',
            name='hidden',
        ),
    ]
