# Generated by Django 4.0.1 on 2022-02-09 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_surveyquestion_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
