# Generated by Django 4.0.1 on 2022-02-19 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0012_surveysession_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysubmission',
            name='survey',
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.surveysession'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='surveysession',
            unique_together={('id', 'owner')},
        ),
    ]
