# Generated by Django 4.0.1 on 2022-02-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_remove_survey_active_remove_survey_end_date_time_and_more'),
        ('survey', '0013_remove_surveysubmission_survey_and_more'),
    ]

    operations = [
    ]
