# Generated by Django 4.0.1 on 2022-02-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_alter_surveysession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='group_by_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_survey', to='survey.surveyquestion'),
        ),
    ]
