# Generated by Django 4.0.1 on 2022-02-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_survey_draft_survey_group_by_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysubmission',
            name='user',
        ),
    ]
